version: '3.8'
services:
  server:
    container_name: misadrawings_server
    build:
      dockerfile: Dockerfile
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - misadrawings-network

  client:
    container_name: misadrawings_client
    build:
      dockerfile: Dockerfile
      context: ./client
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - misadrawings-network

networks:
  misadrawings-network:
    driver: bridge
